
# Java Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: BloggingAppDeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogging-app
  template:
    metadata:
      labels:
        app: blogging-app
    spec:
      containers:
      - name: blogging-app
        image: kavindra123/blogging-app:latest
        imagePullPolicy: IfRequired
        ports:
        - containerPort: 8080
---
# Bank Application Service
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: blogging-app
