name: Github Actions Name is Blogging-Actions
on:
  push:
    branches: [ "main" ]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "Hello World" 
  compile:
    #needs: hello-world
    runs-on: runner1   
    steps:
    - name: Install Maven
      run: sudo apt-get update && sudo apt-get install maven -y
    - uses: actions/checkout@v4 ## First we do Git SCM checkout so that our repo is available in the runner 
      name: Setup JDK
    - uses: actions/setup-java@v4
      with: 
         java-version: '17'
         distribution: 'temurin'
         cache: maven
    - name: Compile the code
      run: mvn compile
  security-check:
    needs: compile
    runs-on: runner1
    steps:
    - uses: actions/checkout@v4
    - name: Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install trivy -y
        
    - name: Run trivy Scan
      run: trivy fs --format=table -o trivy-report.html . 
    - name: Gitleaks Check
      run: sudo apt install gitleaks -y
    - name: Gitleaks Code Scan
      run: gitleaks detect source . -r gitleaks-report.json -f json
  unit-test:
    runs-on: runner1
    #needs: security-check
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run test cases
      run: mvn test
  Build:
    runs-on: self-hosted
    needs: unit-test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build Code
      run: mvn package
  sonarqube:
    runs-on: self-hosted
    needs: Build
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.2.0 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      with:
         pollingTimeoutSec: 600
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}


      

