name: Github Actions Name is Blogging-Actions.
on:
  push:
    branches: [ "main" ]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "Hello World" 
